cron_notify executed..
 2020-07-04 15:56:02.261178: Hello from cron
 2020-07-04 15:56:02.263278: Bye from cron
cron_notify executed..
 2020-07-04 16:02:02.088060: Hello from cron
 2020-07-04 16:02:02.090091: Bye from cron
cron_notify executed..
 2020-07-04 16:08:02.250405: Hello from cron
 2020-07-04 16:08:02.250945: Bye from cron
cron_notify executed..
 2020-07-04 16:14:02.183333: Hello from cron
 2020-07-04 16:14:02.183892: Bye from cron
cron_notify executed..
 2020-07-04 16:20:02.221043: Hello from cron
 2020-07-04 16:20:02.221573: Bye from cron
cron_notify executed..
 2020-07-04 16:26:02.328472: Hello from cron
 2020-07-04 16:26:02.329753: Bye from cron
cron_notify executed..
 2020-07-04 16:32:02.312847: Hello from cron
 2020-07-04 16:32:02.313780: Bye from cron
cron_notify executed..
 2020-07-04 16:38:01.492078: Hello from cron
 2020-07-04 16:38:01.492730: Bye from cron
cron_notify executed..
 2020-07-04 16:43:01.982700: Hello from cron
 2020-07-04 16:43:01.983245: Bye from cron
cron_notify executed..
 2020-07-04 16:49:02.074457: Hello from cron
 2020-07-04 16:49:02.074993: Bye from cron
cron_notify executed..
 2020-07-04 16:55:02.086868: Hello from cron
 2020-07-04 16:55:02.087941: Bye from cron
cron_notify executed..
 2020-07-04 17:01:02.177376: Hello from cron
 2020-07-04 17:01:02.178333: Bye from cron
cron_notify executed..
 2020-07-04 17:07:02.017510: Hello from cron
 2020-07-04 17:07:02.018122: Bye from cron
cron_notify executed..
 2020-07-04 17:13:01.861151: Hello from cron
 2020-07-04 17:13:01.861714: Bye from cron
cron_notify executed..
 2020-07-04 17:18:02.487404: Hello from cron
 2020-07-04 17:18:02.488377: Bye from cron
cron_notify executed..
 2020-07-04 17:24:02.388626: Hello from cron
 2020-07-04 17:24:02.389252: Bye from cron
cron_notify executed..
 2020-07-04 17:30:02.327460: Hello from cron
 2020-07-04 17:30:02.328433: Bye from cron
cron_notify executed..
 2020-07-04 17:36:02.186259: Hello from cron
 2020-07-04 17:36:02.186805: Bye from cron
cron_notify executed..
 2020-07-04 17:42:02.138626: Hello from cron
 2020-07-04 17:42:02.139173: Bye from cron
cron_notify executed..
 2020-07-04 17:48:02.151758: Hello from cron
 2020-07-04 17:48:02.152387: Bye from cron
cron_notify executed..
 2020-07-04 17:54:01.952319: Hello from cron
 2020-07-04 17:54:01.953023: Bye from cron
cron_notify executed..
 2020-07-04 17:59:02.321021: Hello from cron
 2020-07-04 17:59:02.321721: Bye from cron
cron_notify executed..
 2020-07-04 18:05:02.258610: Hello from cron
 2020-07-04 18:05:02.259152: Bye from cron
cron_notify executed..
 2020-07-04 18:11:02.022931: Hello from cron
 2020-07-04 18:11:02.023486: Bye from cron
cron_notify executed..
 2020-07-04 18:17:02.065984: Hello from cron
 2020-07-04 18:17:02.067093: Bye from cron
cron_notify executed..
 2020-07-04 18:23:02.071709: Hello from cron
 2020-07-04 18:23:02.072770: Bye from cron
cron_notify executed..
 2020-07-04 18:29:02.030572: Hello from cron
 2020-07-04 18:29:02.031115: Bye from cron
cron_notify executed..
 2020-07-04 18:34:02.358377: Hello from cron
 2020-07-04 18:34:02.359927: Bye from cron
cron_notify executed..
 2020-07-04 18:40:02.243606: Hello from cron
 2020-07-04 18:40:02.244220: Bye from cron
cron_notify executed..
 2020-07-04 18:46:02.066827: Hello from cron
 2020-07-04 18:46:02.067373: Bye from cron
cron_notify executed..
 2020-07-04 18:52:02.032267: Hello from cron
 2020-07-04 18:52:02.032812: Bye from cron
cron_notify executed..
 2020-07-04 18:58:01.901739: Hello from cron
 2020-07-04 18:58:01.902375: Bye from cron
cron_notify executed..
 2020-07-04 19:03:02.256484: Hello from cron
 2020-07-04 19:03:02.257178: Bye from cron
cron_notify executed..
 2020-07-04 19:09:02.126238: Hello from cron
 2020-07-04 19:09:02.126876: Bye from cron
cron_notify executed..
 2020-07-04 19:15:01.878849: Hello from cron
 2020-07-04 19:15:01.879901: Bye from cron
cron_notify executed..
 2020-07-04 19:20:02.170402: Hello from cron
 2020-07-04 19:20:02.171107: Bye from cron
cron_notify executed..
 2020-07-04 19:26:02.035960: Hello from cron
 2020-07-04 19:26:02.036939: Bye from cron
cron_notify executed..
 2020-07-04 19:32:01.965221: Hello from cron
 2020-07-04 19:32:01.965768: Bye from cron
cron_notify executed..
 2020-07-04 19:38:01.840807: Hello from cron
 2020-07-04 19:38:01.841502: Bye from cron
cron_notify executed..
 2020-07-04 19:43:02.222981: Hello from cron
 2020-07-04 19:43:02.223959: Bye from cron
cron_notify executed..
 2020-07-04 19:49:02.142349: Hello from cron
 2020-07-04 19:49:02.142904: Bye from cron
cron_notify executed..
 2020-07-04 19:55:01.947058: Hello from cron
 2020-07-04 19:55:01.947599: Bye from cron
cron_notify executed..
 2020-07-04 20:00:02.327942: Hello from cron
 2020-07-04 20:00:02.328492: Bye from cron
cron_notify executed..
 2020-07-04 20:06:02.164351: Hello from cron
 2020-07-04 20:06:02.164930: Bye from cron
cron_notify executed..
 2020-07-04 20:12:01.990654: Hello from cron
 2020-07-04 20:12:01.991716: Bye from cron
cron_notify executed..
 2020-07-04 20:18:01.900938: Hello from cron
 2020-07-04 20:18:01.901539: Bye from cron
cron_notify executed..
 2020-07-04 20:23:02.222064: Hello from cron
 2020-07-04 20:23:02.222635: Bye from cron
cron_notify executed..
 2020-07-04 20:29:02.198482: Hello from cron
 2020-07-04 20:29:02.199013: Bye from cron
cron_notify executed..
 2020-07-04 20:35:02.117216: Hello from cron
 2020-07-04 20:35:02.117777: Bye from cron
cron_notify executed..
 2020-07-04 20:41:01.944277: Hello from cron
 2020-07-04 20:41:01.944964: Bye from cron
cron_notify executed..
 2020-07-04 20:46:02.300478: Hello from cron
 2020-07-04 20:46:02.301059: Bye from cron
cron_notify executed..
 2020-07-04 20:52:01.400843: Hello from cron
 2020-07-04 20:52:01.401409: Bye from cron
cron_notify executed..
 2020-07-04 20:57:01.778940: Hello from cron
 2020-07-04 20:57:01.779728: Bye from cron
cron_notify executed..
 2020-07-04 21:03:01.849727: Hello from cron
 2020-07-04 21:03:01.850325: Bye from cron
cron_notify executed..
 2020-07-04 21:08:02.245189: Hello from cron
 2020-07-04 21:08:02.245861: Bye from cron
cron_notify executed..
 2020-07-04 21:14:02.121865: Hello from cron
 2020-07-04 21:14:02.122520: Bye from cron
cron_notify executed..
 2020-07-04 21:20:02.029182: Hello from cron
 2020-07-04 21:20:02.029988: Bye from cron
cron_notify executed..
 2020-07-04 21:26:01.922312: Hello from cron
 2020-07-04 21:26:01.923037: Bye from cron
cron_notify executed..
 2020-07-04 21:32:01.936125: Hello from cron
 2020-07-04 21:32:01.936732: Bye from cron
cron_notify executed..
 2020-07-04 21:37:02.293148: Hello from cron
 2020-07-04 21:37:02.293794: Bye from cron
cron_notify executed..
 2020-07-04 21:43:02.288078: Hello from cron
 2020-07-04 21:43:02.288651: Bye from cron
cron_notify executed..
 2020-07-04 21:49:02.227958: Hello from cron
 2020-07-04 21:49:02.228632: Bye from cron
cron_notify executed..
 2020-07-04 21:55:02.049971: Hello from cron
 2020-07-04 21:55:02.050527: Bye from cron
cron_notify executed..
 2020-07-04 22:01:02.025184: Hello from cron
 2020-07-04 22:01:02.026286: Bye from cron
cron_notify executed..
 2020-07-04 22:06:02.342814: Hello from cron
 2020-07-04 22:06:02.343344: Bye from cron
cron_notify executed..
 2020-07-04 22:12:02.280808: Hello from cron
 2020-07-04 22:12:02.281366: Bye from cron
cron_notify executed..
 2020-07-04 22:18:02.276027: Hello from cron
 2020-07-04 22:18:02.276787: Bye from cron
cron_notify executed..
 2020-07-04 22:24:02.179033: Hello from cron
 2020-07-04 22:24:02.179584: Bye from cron
cron_notify executed..
 2020-07-04 22:30:01.966266: Hello from cron
 2020-07-04 22:30:01.966942: Bye from cron
cron_notify executed..
 2020-07-04 22:35:02.256472: Hello from cron
 2020-07-04 22:35:02.257012: Bye from cron
cron_notify executed..
 2020-07-04 22:41:02.140015: Hello from cron
 2020-07-04 22:41:02.140628: Bye from cron
cron_notify executed..
 2020-07-04 22:47:01.877278: Hello from cron
 2020-07-04 22:47:01.878157: Bye from cron
cron_notify executed..
 2020-07-04 22:52:02.311953: Hello from cron
 2020-07-04 22:52:02.312500: Bye from cron
cron_notify executed..
 2020-07-04 22:58:02.164359: Hello from cron
 2020-07-04 22:58:02.164897: Bye from cron
cron_notify executed..
 2020-07-04 23:04:02.157875: Hello from cron
 2020-07-04 23:04:02.158879: Bye from cron
cron_notify executed..
 2020-07-04 23:10:02.080140: Hello from cron
 2020-07-04 23:10:02.080681: Bye from cron
cron_notify executed..
 2020-07-04 23:16:01.848570: Hello from cron
 2020-07-04 23:16:01.849221: Bye from cron
cron_notify executed..
 2020-07-04 23:21:02.208073: Hello from cron
 2020-07-04 23:21:02.209210: Bye from cron
cron_notify executed..
 2020-07-04 23:27:02.084718: Hello from cron
 2020-07-04 23:27:02.085471: Bye from cron
cron_notify executed..
 2020-07-04 23:33:02.033405: Hello from cron
 2020-07-04 23:33:02.033988: Bye from cron
cron_notify executed..
 2020-07-04 23:38:02.406397: Hello from cron
 2020-07-04 23:38:02.406968: Bye from cron
cron_notify executed..
 2020-07-04 23:44:02.356049: Hello from cron
 2020-07-04 23:44:02.357595: Bye from cron
cron_notify executed..
 2020-07-04 23:50:02.142731: Hello from cron
 2020-07-04 23:50:02.143268: Bye from cron
cron_notify executed..
 2020-07-04 23:56:01.913696: Hello from cron
 2020-07-04 23:56:01.914290: Bye from cron
cron_notify executed..
 2020-07-05 00:01:02.233606: Hello from cron
 2020-07-05 00:01:02.234360: Bye from cron
cron_notify executed..
 2020-07-05 00:07:02.052632: Hello from cron
 2020-07-05 00:07:02.053343: Bye from cron
cron_notify executed..
 2020-07-05 00:13:02.026641: Hello from cron
 2020-07-05 00:13:02.027331: Bye from cron
cron_notify executed..
 2020-07-05 00:19:02.072250: Hello from cron
 2020-07-05 00:19:02.072941: Bye from cron
cron_notify executed..
 2020-07-05 00:25:01.913277: Hello from cron
 2020-07-05 00:25:01.914080: Bye from cron
cron_notify executed..
 2020-07-05 00:30:02.364155: Hello from cron
 2020-07-05 00:30:02.365664: Bye from cron
cron_notify executed..
 2020-07-05 00:36:02.195953: Hello from cron
 2020-07-05 00:36:02.196536: Bye from cron
cron_notify executed..
 2020-07-05 00:42:01.421608: Hello from cron
 2020-07-05 00:42:01.422193: Bye from cron
cron_notify executed..
 2020-07-05 00:47:02.006716: Hello from cron
 2020-07-05 00:47:02.007490: Bye from cron
cron_notify executed..
 2020-07-05 00:52:02.644858: Hello from cron
 2020-07-05 00:52:02.645406: Bye from cron
cron_notify executed..
 2020-07-05 00:58:01.457070: Hello from cron
 2020-07-05 00:58:01.457605: Bye from cron
cron_notify executed..
 2020-07-05 01:03:01.598320: Hello from cron
 2020-07-05 01:03:01.598852: Bye from cron
cron_notify executed..
 2020-07-05 01:08:01.742491: Hello from cron
 2020-07-05 01:08:01.743029: Bye from cron
cron_notify executed..
 2020-07-05 01:13:01.889392: Hello from cron
 2020-07-05 01:13:01.889950: Bye from cron
cron_notify executed..
 2020-07-05 01:18:02.005650: Hello from cron
 2020-07-05 01:18:02.006232: Bye from cron
cron_notify executed..
 2020-07-05 01:24:01.891872: Hello from cron
 2020-07-05 01:24:01.892435: Bye from cron
cron_notify executed..
 2020-07-05 01:30:01.795399: Hello from cron
 2020-07-05 01:30:01.795996: Bye from cron
cron_notify executed..
 2020-07-05 01:35:01.955737: Hello from cron
 2020-07-05 01:35:01.956271: Bye from cron
cron_notify executed..
 2020-07-05 01:40:02.090033: Hello from cron
 2020-07-05 01:40:02.090571: Bye from cron
cron_notify executed..
 2020-07-05 01:45:02.240303: Hello from cron
 2020-07-05 01:45:02.240841: Bye from cron
cron_notify executed..
 2020-07-05 01:51:01.817453: Hello from cron
 2020-07-05 01:51:01.818061: Bye from cron
cron_notify executed..
 2020-07-05 01:56:02.012643: Hello from cron
 2020-07-05 01:56:02.013205: Bye from cron
cron_notify executed..
 2020-07-05 02:01:02.176623: Hello from cron
 2020-07-05 02:01:02.177191: Bye from cron
cron_notify executed..
 2020-07-05 02:07:01.976235: Hello from cron
 2020-07-05 02:07:01.976889: Bye from cron
cron_notify executed..
 2020-07-05 02:13:02.070290: Hello from cron
 2020-07-05 02:13:02.071204: Bye from cron
cron_notify executed..
 2020-07-05 02:19:01.898837: Hello from cron
 2020-07-05 02:19:01.899376: Bye from cron
cron_notify executed..
 2020-07-05 02:24:02.047207: Hello from cron
 2020-07-05 02:24:02.047746: Bye from cron
cron_notify executed..
 2020-07-05 02:30:02.033851: Hello from cron
 2020-07-05 02:30:02.034555: Bye from cron
cron_notify executed..
 2020-07-05 02:36:01.919138: Hello from cron
 2020-07-05 02:36:01.919675: Bye from cron
cron_notify executed..
 2020-07-05 02:41:02.095473: Hello from cron
 2020-07-05 02:41:02.096001: Bye from cron
cron_notify executed..
 2020-07-05 02:46:02.241871: Hello from cron
 2020-07-05 02:46:02.242477: Bye from cron
cron_notify executed..
 2020-07-05 02:52:01.835184: Hello from cron
 2020-07-05 02:52:01.835759: Bye from cron
cron_notify executed..
 2020-07-05 02:57:01.980591: Hello from cron
 2020-07-05 02:57:01.981392: Bye from cron
cron_notify executed..
 2020-07-06 14:08:02.482947: Hello from cron
 2020-07-06 14:08:02.484172: Bye from cron
cron_notify executed..
 2020-07-06 19:05:02.173216: Hello from cron
 2020-07-06 19:05:02.174027: Bye from cron
cron_notify executed..
 2020-07-06 19:22:02.646149: Hello from cron
 2020-07-06 19:22:02.646975: Bye from cron
cron_notify executed..
 2020-07-06 19:55:02.781616: Hello from cron
 2020-07-06 19:55:02.783440: Bye from cron
cron_notify executed..
 2020-07-06 20:08:03.141201: Hello from cron
 2020-07-06 20:08:03.145926: Bye from cron
cron_notify executed..
 2020-07-06 20:14:02.819485: Hello from cron
 2020-07-06 20:14:02.820955: Bye from cron
cron_notify executed..
 2020-07-06 20:20:01.914827: Hello from cron
 2020-07-06 20:20:01.918163: Bye from cron
cron_notify executed..
 2020-07-06 20:25:01.985773: Hello from cron
 2020-07-06 20:25:01.986311: Bye from cron
cron_notify executed..
 2020-07-06 20:30:02.068250: Hello from cron
 2020-07-06 20:30:02.068837: Bye from cron
cron_notify executed..
 2020-07-06 20:35:02.134921: Hello from cron
 2020-07-06 20:35:02.135485: Bye from cron
cron_notify executed..
 2020-07-06 20:40:02.214945: Hello from cron
 2020-07-06 20:40:02.215482: Bye from cron
cron_notify executed..
 2020-07-06 20:45:02.317892: Hello from cron
 2020-07-06 20:45:02.318429: Bye from cron
cron_notify executed..
 2020-07-06 20:51:01.814259: Hello from cron
 2020-07-06 20:51:01.814816: Bye from cron
cron_notify executed..
 2020-07-06 20:56:01.970799: Hello from cron
 2020-07-06 20:56:01.971443: Bye from cron
cron_notify executed..
 2020-07-06 21:01:02.060682: Hello from cron
 2020-07-06 21:01:02.061267: Bye from cron
cron_notify executed..
 2020-07-06 21:06:02.123179: Hello from cron
 2020-07-06 21:06:02.123711: Bye from cron
cron_notify executed..
 2020-07-06 21:11:02.195584: Hello from cron
 2020-07-06 21:11:02.196142: Bye from cron
cron_notify executed..
 2020-07-06 21:16:02.252037: Hello from cron
 2020-07-06 21:16:02.252591: Bye from cron
cron_notify executed..
 2020-07-06 21:21:02.313778: Hello from cron
 2020-07-06 21:21:02.314314: Bye from cron
cron_notify executed..
 2020-07-06 21:27:01.797178: Hello from cron
 2020-07-06 21:27:01.797720: Bye from cron
cron_notify executed..
 2020-07-06 21:32:01.873731: Hello from cron
 2020-07-06 21:32:01.874368: Bye from cron
cron_notify executed..
 2020-07-06 21:37:01.945350: Hello from cron
 2020-07-06 21:37:01.945884: Bye from cron
cron_notify executed..
 2020-07-06 21:42:02.007327: Hello from cron
 2020-07-06 21:42:02.007883: Bye from cron
cron_notify executed..
 2020-07-06 21:47:02.093748: Hello from cron
 2020-07-06 21:47:02.094308: Bye from cron
cron_notify executed..
 2020-07-06 21:52:02.154308: Hello from cron
 2020-07-06 21:52:02.154840: Bye from cron
cron_notify executed..
 2020-07-06 21:58:01.907371: Hello from cron
 2020-07-06 21:58:01.908046: Bye from cron
cron_notify executed..
 2020-07-06 22:03:02.405196: Hello from cron
 2020-07-06 22:03:02.405765: Bye from cron
cron_notify executed..
 2020-07-06 22:09:02.260316: Hello from cron
 2020-07-06 22:09:02.260917: Bye from cron
cron_notify executed..
 2020-07-06 22:15:02.096183: Hello from cron
 2020-07-06 22:15:02.097496: Bye from cron
cron_notify executed..
 2020-07-06 22:21:02.184444: Hello from cron
 2020-07-06 22:21:02.185239: Bye from cron
cron_notify executed..
 2020-07-06 22:27:01.567917: Hello from cron
 2020-07-06 22:27:01.568769: Bye from cron
cron_notify executed..
 2020-07-06 22:32:02.088920: Hello from cron
 2020-07-06 22:32:02.089477: Bye from cron
cron_notify executed..
 2020-07-06 22:38:02.337133: Hello from cron
 2020-07-06 22:38:02.337852: Bye from cron
cron_notify executed..
 2020-07-06 22:44:01.676560: Hello from cron
 2020-07-06 22:44:01.677340: Bye from cron
cron_notify executed..
 2020-07-06 22:49:02.671439: Hello from cron
 2020-07-06 22:49:02.676611: Bye from cron
cron_notify executed..
 2020-07-06 22:55:01.986439: Hello from cron
 2020-07-06 22:55:01.986998: Bye from cron
cron_notify executed..
 2020-07-06 23:08:02.137473: Hello from cron
 2020-07-06 23:08:02.138406: Bye from cron
cron_notify executed..
 2020-07-06 23:14:01.875305: Hello from cron
 2020-07-06 23:14:01.876349: Bye from cron
cron_notify executed..
 2020-07-06 23:19:02.046293: Hello from cron
 2020-07-06 23:19:02.047020: Bye from cron
cron_notify executed..
 2020-07-06 23:25:02.328025: Hello from cron
 2020-07-06 23:25:02.328672: Bye from cron
cron_notify executed..
 2020-07-06 23:31:01.600812: Hello from cron
 2020-07-06 23:31:01.601371: Bye from cron
cron_notify executed..
 2020-07-06 23:36:02.328742: Hello from cron
 2020-07-06 23:36:02.329609: Bye from cron
cron_notify executed..
 2020-07-06 23:41:02.434762: Hello from cron
 2020-07-06 23:41:02.435767: Bye from cron
cron_notify executed..
 2020-07-06 23:46:02.437826: Hello from cron
 2020-07-06 23:46:02.438959: Bye from cron
cron_notify executed..
 2020-07-06 23:52:01.518372: Hello from cron
 2020-07-06 23:52:01.519012: Bye from cron
cron_notify executed..
 2020-07-06 23:57:02.137009: Hello from cron
 2020-07-06 23:57:02.137606: Bye from cron
cron_notify executed..
 2020-07-07 00:03:02.063358: Hello from cron
 2020-07-07 00:03:02.064488: Bye from cron
cron_notify executed..
 2020-07-07 00:09:02.239448: Hello from cron
 2020-07-07 00:09:02.240857: Bye from cron
cron_notify executed..
 2020-07-07 00:14:02.448732: Hello from cron
 2020-07-07 00:14:02.449297: Bye from cron
cron_notify executed..
 2020-07-07 00:20:02.351343: Hello from cron
 2020-07-07 00:20:02.352250: Bye from cron
cron_notify executed..
 2020-07-07 00:25:02.379526: Hello from cron
 2020-07-07 00:25:02.380201: Bye from cron
cron_notify executed..
 2020-07-07 00:31:02.978047: Hello from cron
 2020-07-07 00:31:02.978735: Bye from cron
cron_notify executed..
 2020-07-07 00:37:02.804153: Hello from cron
 2020-07-07 00:37:02.806610: Bye from cron
cron_notify executed..
 2020-07-07 00:43:02.210440: Hello from cron
 2020-07-07 00:43:02.211003: Bye from cron
cron_notify executed..
 2020-07-07 00:49:02.185064: Hello from cron
 2020-07-07 00:49:02.185786: Bye from cron
cron_notify executed..
 2020-07-07 00:55:01.428702: Hello from cron
 2020-07-07 00:55:01.429344: Bye from cron
cron_notify executed..
 2020-07-07 01:00:02.089251: Hello from cron
 2020-07-07 01:00:02.090006: Bye from cron
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
cron_notify executed..
 2020-07-07 01:05:02.589028: Hello from cron
 2020-07-07 01:05:02.589581: Bye from cron
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
cron_notify executed..
 2020-07-07 01:11:01.667761: Hello from cron
 2020-07-07 01:11:01.668575: Bye from cron
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
cron_notify executed..
 2020-07-07 01:16:02.046860: Hello from cron
 2020-07-07 01:16:02.047756: Bye from cron
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
['/home/user/django/maap', '/home/user', '/home/user/django/maap/mainapp', '/home/user/django', '/home/user/django/env/lib/python38.zip', '/home/user/django/env/lib/python3.8', '/home/user/django/env/lib/python3.8/lib-dynload', '/opt/python/3.8.0/lib/python3.8', '/home/user/django/env/lib/python3.8/site-packages', '/home/user/django/maap/mainapp', '/home/user/django']
cron_notify executed..
 2020-07-07 01:22:01.882911: Hello from cron
 2020-07-07 01:22:01.883531: Bye from cron
cron_notify executed..
 2020-07-07 01:27:02.337231: Hello from cron
 2020-07-07 01:27:02.337914: Bye from cron
cron_notify executed..
 2020-07-07 01:32:02.410953: Hello from cron
 2020-07-07 01:32:02.411711: Bye from cron
cron_notify executed..
 2020-07-07 01:38:02.478424: Hello from cron
 2020-07-07 01:38:02.479771: Bye from cron
cron_notify executed..
 2020-07-07 01:44:02.183850: Hello from cron
 2020-07-07 01:44:02.185187: Bye from cron
cron_notify executed..
 2020-07-07 01:49:02.394532: Hello from cron
 2020-07-07 01:49:02.395302: Bye from cron
cron_notify executed..
 2020-07-07 01:55:02.512397: Hello from cron
 2020-07-07 01:55:02.514157: Bye from cron
cron_notify executed..
 2020-07-07 02:01:01.518194: Hello from cron
 2020-07-07 02:01:01.518761: Bye from cron
cron_notify executed..
 2020-07-07 02:06:01.747672: Hello from cron
 2020-07-07 02:06:01.748218: Bye from cron
cron_notify executed..
 2020-07-07 02:11:01.759547: Hello from cron
 2020-07-07 02:11:01.760314: Bye from cron
cron_notify executed..
 2020-07-07 02:16:02.343800: Hello from cron
 2020-07-07 02:16:02.344407: Bye from cron
cron_notify executed..
 2020-07-07 03:45:10.527485: Hello from cron
 2020-07-07 03:45:10.531853: Bye from cron
cron_notify executed..
 2020-07-07 03:51:02.283569: Hello from cron
 2020-07-07 03:51:02.284311: Bye from cron
cron_notify executed..
 2020-07-07 03:57:02.086078: Hello from cron
 2020-07-07 03:57:02.086683: Bye from cron
cron_notify executed..
 2020-07-07 04:02:02.422627: Hello from cron
 2020-07-07 04:02:02.423949: Bye from cron
cron_notify executed..
 2020-07-07 04:08:02.150191: Hello from cron
 2020-07-07 04:08:02.151023: Bye from cron
cron_notify executed..
 2020-07-07 04:13:03.043093: Hello from cron
 2020-07-07 04:13:03.044741: Bye from cron
cron_notify executed..
 2020-07-07 04:19:02.819233: Hello from cron
 2020-07-07 04:19:02.820932: Bye from cron
cron_notify executed..
 2020-07-07 04:25:02.631771: Hello from cron
 2020-07-07 04:25:02.633371: Bye from cron
cron_notify executed..
 2020-07-07 04:31:02.031867: Hello from cron
 2020-07-07 04:31:02.032630: Bye from cron
cron_notify executed..
 2020-07-07 04:36:02.225236: Hello from cron
 2020-07-07 04:36:02.225827: Bye from cron
cron_notify executed..
 2020-07-07 04:42:01.691127: Hello from cron
 2020-07-07 04:42:01.691678: Bye from cron
cron_notify executed..
 2020-07-07 04:47:02.337828: Hello from cron
 2020-07-07 04:47:02.338387: Bye from cron
cron_notify executed..
 2020-07-07 04:53:02.233578: Hello from cron
 2020-07-07 04:53:02.234250: Bye from cron
cron_notify executed..
 2020-07-07 04:59:02.121298: Hello from cron
 2020-07-07 04:59:02.121908: Bye from cron
cron_notify executed..
 2020-07-07 05:05:02.132391: Hello from cron
 2020-07-07 05:05:02.134185: Bye from cron
cron_notify executed..
 2020-07-07 05:11:01.610999: Hello from cron
 2020-07-07 05:11:01.611938: Bye from cron
cron_notify executed..
 2020-07-09 00:21:02.678347: Hello from cron
 2020-07-09 00:21:02.679175: Bye from cron
cron_notify executed..
 2020-07-09 00:27:01.519459: Hello from cron
 2020-07-09 00:27:01.520086: Bye from cron
cron_notify executed..
 2020-07-09 00:33:02.427524: Hello from cron
 2020-07-09 00:33:02.428879: Bye from cron
cron_notify executed..
 2020-07-09 00:39:02.353323: Hello from cron
 2020-07-09 00:39:02.354151: Bye from cron
cron_notify executed..
 2020-07-09 00:45:01.548722: Hello from cron
 2020-07-09 00:45:01.549294: Bye from cron
cron_notify executed..
 2020-07-09 00:51:01.908737: Hello from cron
 2020-07-09 00:51:01.909783: Bye from cron
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "<fstring>", line 1
    ('раз в 3 дня' if rem_period == 3 elif rem_period 'раз в неделю')
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "/home/user/django/maap/mainapp/_mailsend.py", line 29
    rem_period = lambda ()
                        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "/home/user/django/maap/mainapp/_mailsend.py", line 29
    rem_period = lambda ()
                        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "/home/user/django/maap/mainapp/_mailsend.py", line 29
    rem_period = lambda ()
                        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "/home/user/django/maap/mainapp/_mailsend.py", line 29
    rem_period = lambda ()
                        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/user/django/maap/manage.py", line 22, in <module>
    main()
  File "/home/user/django/maap/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/django/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/django/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/django/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/django/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/django/maap/maap/urls.py", line 23, in <module>
    import mainapp.views as mainapp
  File "/home/user/django/maap/mainapp/views.py", line 17, in <module>
    from cron import cron_notify
  File "/home/user/django/maap/mainapp/cron.py", line 7, in <module>
    from _mailsend import mail_notify
  File "/home/user/django/maap/mainapp/_mailsend.py", line 29
    rem_period = lambda ()
                        ^
SyntaxError: invalid syntax
cron_notify executed..
 2020-07-09 01:10:02.266552: Hello from cron
 2020-07-09 01:10:02.267212: Bye from cron
cron_notify executed..
 2020-07-09 01:16:01.678617: Hello from cron
 2020-07-09 01:16:01.679154: Bye from cron
cron_notify executed..
 2020-07-09 01:22:02.103553: Hello from cron
 2020-07-09 01:22:02.104199: Bye from cron
cron_notify executed..
 2020-07-09 01:28:01.531708: Hello from cron
 2020-07-09 01:28:01.532284: Bye from cron
cron_notify executed..
 2020-07-09 01:33:02.060119: Hello from cron
 2020-07-09 01:33:02.060713: Bye from cron
